# Generated by Django 6.0 on 2025-12-03 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad_asientos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('anio_fabricacion', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('licencia_tipo', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('duracion_estimada_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('terminal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='core.terminal')),
                ('terminal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='core.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField()),
                ('fecha_hora_llegada_estimada', models.DateTimeField()),
                ('duracion_estimada_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.conductor')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.ruta')),
            ],
        ),
    ]
